{{- if and (not .Values.gatewayToken.existingSecret.name) .Values.gatewayToken.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw.fullname" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  gateway-token: {{ .Values.gatewayToken.value | quote }}
{{- end }}
