{{- if and (not .Values.existingSecret) .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{include "openclaw.fullname" .}}
  labels:
    {{- include "openclaw.labels" . | nindent 4}}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets}}
  {{$key}}: {{$value | quote}}
{{- end}}
{{- end}}
